---
title: "Teaching my Dad Neuorimaging Experiment Protocols"
author: "Christina Fan"
date: "2025-09-10"
categories: [research, teaching]
---

This is a summary of an experiment protocol I wrote for my dad before he went to participate in an neuroimaging experiment last year;
he was concerned his English wasn't proficient enough to understand all the experiment steps, so I translated everything in Chinese (his native language) for him.
I actually also want to see if I can upload posts with non-English characters onto the blog.

实验概要：

一共分两次， 你得去两趟，每次2-3个小时：

第一次：实验者给你介绍你要干吗，介绍完了你可以提问，如果愿意参加实验就填授权表。授权后会提问你的身体健康现况有没有资格参加实验（这个你已经达标了，你没有什么神经心脏疾病，身体里没有金属物品，Blah blah)
1. 先得测试你的视力，4个视力测试就是基本的那种离一段距离，问你看到的是什么，物体是从哪个方向朝你来，看到多少个物体，blah blah, 很basic。
2. 心理测试，一共三个：
a. Binocular Rivalry: 这个好像也是一种视力测试，中文叫双眼竞争，你自己去看我给你发的翻译版本的第三页吧。
b. Simultaneity Task: 你坐在电脑面前，屏幕前会给你闪现一个小方块，也会播放一个beep声音。你得判断声音播放和方块闪现是否同时发生，觉得是同时就按某一个键，觉得不是就按另一个键。这个会做个5-10分钟，有时候是同时发生，有时候不是。
c. Temporal Order Judgement Task: 和上面那个一样，但是现在是问你哪个先发生，方块还是beep声音。也做个5-10分钟吧。
3. MRI: 工作人员会指导你要进MRI之前的注意事项（你身上不能有任何金属物品不然会危害身体，得换上某种衣服, 戴上耳塞保护耳朵, 具体的还有）。你会在MRI里躺40分钟，会给你一个小东西来和他们沟通（如果你想出去可以随时通过这个告诉他们）。
4. 从MRI里出来后会给你进行脑电波刺激。会用胶和一些什么橡皮往你脑袋上按上那个电波仪器。刺激的时候可能会感觉痒，发热因为你的脑袋那块会短暂的增加血液流淌。不常见，但有些人可能会头痛或者想吐。如果你出现这些症状他们会停止实验让你下去吃药/休息。脑电波刺激是要20分钟。
5. 刺激完了你再进去MRI里躺个40分钟。

那个顺序肯定是MRI->脑电波刺激->MRI，但心理测试可能先测也可能后面测。

第二次实验的流程和第一次是一样的，唯一的区别是有一次是真的在给你进行脑电波刺激，另一次是假的。重点就是这些，实验背后的理论你感兴趣的话可以读一下他的介绍或者问我，详细的细节他会下周发过来。你去的时候他也会再给你讲解一遍，你有不懂的地方就问，实验就是要保证越准确越好。